SRC = src
OBJ = obj
BIN = bin
INC = include

all: $(BIN)/ejecutable

$(BIN)/ejecutable: $(OBJ)/Equipo.o $(INC)/Equipo.hpp $(INC)/ComponenteEquipo.hpp $(INC)/VisitanteEquipo.hpp $(INC)/VisitantePrecio.hpp $(INC)/VisitantePrecioDetalle.hpp
	g++ 