
package p1s4;


public class Salpicadero extends javax.swing.JPanel {
    
    public Salpicadero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        velocimetro = new p1s4.Velocimetro();
        cuentaKilometros = new p1s4.CuentaKilometros();
        cuentaRevoluciones = new p1s4.CuentaRevoluciones();

        setLayout(new java.awt.GridLayout(3, 1));

        velocimetro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(velocimetro);

        cuentaKilometros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(cuentaKilometros);

        cuentaRevoluciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(cuentaRevoluciones);
    }// </editor-fold>//GEN-END:initComponents

    // Métodos consultores:
    
    public CuentaKilometros getCuentaKilometros() {
        return cuentaKilometros;
    }

    public CuentaRevoluciones getCuentaRevoluciones() {
        return cuentaRevoluciones;
    }

    public Velocimetro getVelocimetro() {
        return velocimetro;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private p1s4.CuentaKilometros cuentaKilometros;
    private p1s4.CuentaRevoluciones cuentaRevoluciones;
    private p1s4.Velocimetro velocimetro;
    // End of variables declaration//GEN-END:variables
}
