/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p1s4;


public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Mandos
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JTabbedPane();
        panelBotones = new p1s4.PanelBotones();
        salpicadero = new p1s4.Salpicadero();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.addTab("Panel Botones", panelBotones);
        panelPrincipal.addTab("Salpicadero", salpicadero);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Salpicadero getSalpicadero() {
        return salpicadero;
    }

    public PanelBotones getPanelBotones() {
        return panelBotones;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private p1s4.PanelBotones panelBotones;
    private javax.swing.JTabbedPane panelPrincipal;
    private p1s4.Salpicadero salpicadero;
    // End of variables declaration//GEN-END:variables
}
