
package p2;

import javax.swing.JTextField;


public class CuentaKilometros extends javax.swing.JPanel {

    // *************************************************************************
    // CONSTRUCTOR:
    // *************************************************************************
    
    
    public CuentaKilometros() {
        initComponents();
        Speedometer sp = new Speedometer();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaPrincipal = new javax.swing.JLabel();
        distanciaReciente = new javax.swing.JTextField();
        etiquetaDisReciente = new javax.swing.JLabel();
        etiquetaDistancia = new javax.swing.JLabel();
        distancia = new javax.swing.JTextField();

        etiquetaPrincipal.setText("Cuenta Kilómetros");
        etiquetaPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiquetaDisReciente.setText("km (actual)");

        etiquetaDistancia.setText("km (acumulado)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 380, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaDisReciente)
                    .addComponent(etiquetaDistancia))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distanciaReciente, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(etiquetaPrincipal)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distanciaReciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaDisReciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDistancia)
                    .addComponent(distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents


    // *************************************************************************
    // MÉTODOS CONSULTORES:
    // *************************************************************************
    

    public JTextField getDistanciaReciente() {
        return distanciaReciente;
    }
    
    public JTextField getDistancia() {
        return distancia;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField distancia;
    private javax.swing.JTextField distanciaReciente;
    private javax.swing.JLabel etiquetaDisReciente;
    private javax.swing.JLabel etiquetaDistancia;
    private javax.swing.JLabel etiquetaPrincipal;
    // End of variables declaration//GEN-END:variables
}
