
package p2;

import p2.ControlCombustible;
import p2.CuentaKilometros;
import p2.CuentaRevoluciones;
import p2.Controlador;


public class Salpicadero extends javax.swing.JPanel{
    private Controlador controlador;
    
    // *************************************************************************
    // CONSTRUCTOR:
    // *************************************************************************
    
    public Salpicadero() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        velocimetro = new p2.Velocimetro();
        cuentaKilometros = new p2.CuentaKilometros();
        cuentaRevoluciones = new p2.CuentaRevoluciones();
        controlCombustible1 = new p2.ControlCombustible();

        setLayout(new java.awt.GridLayout(2, 2));

        velocimetro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(velocimetro);

        cuentaKilometros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(cuentaKilometros);

        cuentaRevoluciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(cuentaRevoluciones);
        add(controlCombustible1);
    }// </editor-fold>//GEN-END:initComponents

    // *************************************************************************
    // MÉTODOS CONSULTORES:
    // *************************************************************************
    
    public CuentaKilometros getCuentaKilometros() {
        return cuentaKilometros;
    }

    public CuentaRevoluciones getCuentaRevoluciones() {
        return cuentaRevoluciones;
    }

    public Velocimetro getVelocimetro() {
        return velocimetro;
    }

    public ControlCombustible getControlCombustible() {
        return controlCombustible1;
    }
    
    // *************************************************************************
    // MÉTODOS MODIFICADORES:
    // *************************************************************************
    
    public void setControlador(Controlador c){
        controlador = c;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private p2.ControlCombustible controlCombustible1;
    private p2.CuentaKilometros cuentaKilometros;
    private p2.CuentaRevoluciones cuentaRevoluciones;
    private p2.Velocimetro velocimetro;
    // End of variables declaration//GEN-END:variables
}
