/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p1s4;

import java.awt.Color;


public class PanelBotones extends javax.swing.JPanel {
    private EstadoMotor estado_motor = EstadoMotor.APAGADO;
    /**
     * Creates new form PanelBotones
     */
    public PanelBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        etiquetaPrincipal = new javax.swing.JLabel();
        avisoVelocidad = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        botonEncender = new javax.swing.JToggleButton();
        botonAcelerar = new javax.swing.JToggleButton();
        botonFrenar = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridLayout(2, 1));

        panelSuperior.setLayout(new java.awt.BorderLayout());

        etiquetaPrincipal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        etiquetaPrincipal.setForeground(java.awt.Color.red);
        etiquetaPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaPrincipal.setText("APAGADO");
        etiquetaPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSuperior.add(etiquetaPrincipal, java.awt.BorderLayout.CENTER);

        avisoVelocidad.setBackground(new java.awt.Color(204, 204, 204));
        avisoVelocidad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        avisoVelocidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelSuperior.add(avisoVelocidad, java.awt.BorderLayout.PAGE_START);

        add(panelSuperior);

        botonEncender.setForeground(java.awt.Color.green);
        botonEncender.setText("ENCENDER");
        botonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEncenderActionPerformed(evt);
            }
        });
        panelInferior.add(botonEncender);

        botonAcelerar.setText("ACELERAR");
        botonAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcelerarActionPerformed(evt);
            }
        });
        panelInferior.add(botonAcelerar);

        botonFrenar.setText("FRENAR");
        botonFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFrenarActionPerformed(evt);
            }
        });
        panelInferior.add(botonFrenar);

        add(panelInferior);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcelerarActionPerformed
        if (botonEncender.isSelected()){
            if (botonAcelerar.isSelected()){
                botonAcelerar.setForeground(Color.red);
                botonAcelerar.setText("Soltar acelerador");
                etiquetaPrincipal.setText("ACELERANDO");
                estado_motor = EstadoMotor.ACELERANDO;
                
                if(botonFrenar.isSelected()){
                    botonFrenar.setForeground(Color.black);
                    botonFrenar.setText("FRENAR");
                    botonFrenar.setSelected(false);
                }
            }
            else{
                botonAcelerar.setForeground(Color.black);
                botonAcelerar.setText("ACELERAR");
                etiquetaPrincipal.setText("ENCENDIDO");
                estado_motor = EstadoMotor.ENCENDIDO;
            }
        }
        else
            botonAcelerar.setSelected(false);
    }//GEN-LAST:event_botonAcelerarActionPerformed

    private void botonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEncenderActionPerformed
        if (botonEncender.isSelected()){
            botonEncender.setForeground(Color.red);
            botonEncender.setText("APAGAR");
            etiquetaPrincipal.setText("ENCENDIDO");
            estado_motor = EstadoMotor.ENCENDIDO;
        }
        else {
            botonEncender.setForeground(Color.green);
            botonEncender.setText("ENCENDER");
            
            if (botonAcelerar.isSelected()){
                botonAcelerar.setForeground(Color.black);
                botonAcelerar.setText("ACELERAR");
                botonAcelerar.setSelected(false);
            }
            
            if (botonFrenar.isSelected()){
                botonFrenar.setForeground(Color.black);
                botonFrenar.setText("FRENAR");
                botonFrenar.setSelected(false);
            }
            
            etiquetaPrincipal.setText("APAGADO");
            estado_motor = EstadoMotor.APAGADO;
        }
    }//GEN-LAST:event_botonEncenderActionPerformed

    private void botonFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFrenarActionPerformed
        
        if (botonEncender.isSelected()){
        
            if (botonFrenar.isSelected()){
                botonFrenar.setForeground(Color.red);
                botonFrenar.setText("Soltar freno");
                etiquetaPrincipal.setText("FRENANDO");
                estado_motor = EstadoMotor.FRENANDO;
                
                if (botonAcelerar.isSelected()){
                    botonAcelerar.setForeground(Color.black);
                    botonAcelerar.setText("ACELERAR");
                    botonAcelerar.setSelected(false);
                }
            }else{
                botonFrenar.setForeground(Color.black);
                botonFrenar.setText("FRENAR");
                etiquetaPrincipal.setText("ENCENDIDO");
                estado_motor = EstadoMotor.ENCENDIDO;
            }
        }
        else
            botonFrenar.setSelected(false);
    }//GEN-LAST:event_botonFrenarActionPerformed

    
    // Métodos consultores:
    public EstadoMotor getEstadoMotor() {
        return estado_motor;
    }

    // Métodos para activar/desactivar mensaje de aviso:
    public void activarAvisoVelocidad(){
        avisoVelocidad.setText("¡ATENCIÓN!  MODERE SU VELOCIDAD");
    }
    
    public void desactivarAvisoVelocidad(){
        avisoVelocidad.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoVelocidad;
    private javax.swing.JToggleButton botonAcelerar;
    private javax.swing.JToggleButton botonEncender;
    private javax.swing.JToggleButton botonFrenar;
    private javax.swing.JLabel etiquetaPrincipal;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
}
